name: Test dependancy compatibility

on:
  push:
    paths:
      - "requirements.txt"
      - ".github/workflows/1.test-deps.yml"
    branches: ["senpai"]
  pull_request:
    paths:
      - "requirements.txt"
      - ".github/workflows/1.test-deps.yml"
    branches: ["senpai"]

jobs:
  test_deps_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test_deps_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run on arm64
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: |
            DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y python3.9 python3.9-dev python3.9-venv python3.9-distutils python3.9-pip
            python3.9 -m pip install --upgrade pip
            pip install -r requirements.txt
