name: Build container and push to GHCR

on:
  workflow_run:
    workflows: ["Test dependancy compatibility"]
    branches: [senpai]
    types: 
      - completed
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/buzz-utils-bot:latest
            ghcr.io/${{ github.repository_owner }}/buzz-utils-bot:latest-arm64
            ghcr.io/${{ github.repository_owner }}/buzz-utils-bot:${{ github.sha }}
          labels: |
            org.opencontainers.image.description = "A utility bot for Discord."
