name: Build container and push to GHCR

on:
  push:
    branches: ["senpai"]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        archs: [linux/amd64, linux/arm64/v8]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (amd64)
        uses: docker/build-push-action@v5
        if: matrix.archs == 'linux/amd64'
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/buzz-utils-bot:latest
            ghcr.io/${{ github.repository_owner }}/buzz-utils-bot:${{ github.sha }}

      - name: Build and push Docker image (arm64)
        uses: docker/build-push-action@v5
        if: matrix.archs == 'linux/arm64/v8'
        with:
          context: .
          file: ./Dockerfile.arm64
          platforms: linux/arm64/v8
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/buzz-utils-bot:latest-arm64
            ghcr.io/${{ github.repository_owner }}/buzz-utils-bot:${{ github.sha }}-arm64
